repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: cargo-check
        args:
          - -F
          - cli
      - id: fmt
      - id: clippy
        args:
          - -F
          - cli

  - repo: .
    rev: HEAD
    hooks:
      - id: nb-check
