---
- id: nb-lint
  name: nb lint
  description: Check changelog with 'nb lint'
  entry: nb lint
  files: 'CHANGELOG.md'
  language: rust
  additional_dependencies:
    - cli:clap
    - cli:owo-colors
    - cli:serde_json
