repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: cargo-check
        args:
          - -F
          - cli
      - id: fmt
      - id: clippy
        args:
          - -F
          - cli

  - repo: .
    rev: 809810b0dc728905e64f67e5dd8cfc2ee790fedc
    hooks:
      - id: nb-lint
